name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  GO111MODULE: on

permissions:
  contents: read

jobs:
  test-unix:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu
          - macOS
        go:
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
    name: "${{ matrix.platform }} | 1.${{ matrix.go }}.x"
    runs-on: ${{ matrix.platform }}-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.${{ matrix.go }}.x
          cache: true

      - run: |
          export GOBIN=$HOME/go/bin
          go install github.com/kyoh86/richgo@latest
          go install github.com/mitchellh/gox@latest

      - run: RICHGO_FORCE_COLOR=1 PATH=$HOME/go/bin/:$PATH make richtest
